#!/usr/bin/env bash

make all
./decaf_compiler $1 2> ll.s > IR.txt

#check the second argument and then retain the intermediate files only if 2nd arg is 1
if [ "$2" ]; then
	if [ $2 -ne 1 ]; then
		make clean
	fi
else
	make clean_intermediate
fi
